### ISSUE TITLE
Not Able to Open

### ISSUE THREAD

**Issue by upadhyayankit04** [Ademking/InstaFollower#4]
This error is coming up unable to fix.

![error](https://user-images.githubusercontent.com/73577232/97421838-fab29980-1932-11eb-9700-e27c0bb357fe.jpg)

**Comment by Ademking** [comment]
This is not how to run this project. Please read documentation
Node is required to use this project
inside the folder, run
`npm install`
After the installation is complete, run
`node app.js`
